
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geomancy_development

test:
  <<: *default
  database: geomancy_test

production:
  <<: *default
  database: geomancy_production
  username: geomancy
  password: <%= ENV['GEOMANCY_DATABASE_PASSWORD'] %>
