
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mergoat_development

test:
  <<: *default
  database: mergoat_test

production:
  <<: *default
  database: mergoat_production
  username: mergoat
  password: <%= ENV['MERGOAT_DATABASE_PASSWORD'] %>
